[server]
port = 8501
address = "0.0.0.0"

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFEDF1"
secondaryBackgroundColor = "#FFC5D0"
textColor = "#262730"
font = "sans serif"
